
import{descriptor,detectOverlap,bestOrder,makePlan}from'./core.mjs';
const $=s=>document.querySelector(s),S={clips:[],analyses:new Map,overlaps:[],plan:null,busy:false,msg:''};
const DB='cutroom-independent-v1',CHUNK=4*1024*1024;let db,key=null;
const enc=new TextEncoder(),dec=new TextDecoder(),b64=u=>btoa(String.fromCharCode(...u)),unb=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
function req(r){return new Promise((a,b)=>{r.onsuccess=()=>a(r.result);r.onerror=()=>b(r.error)})}
function tx(st,m='readonly'){return db.transaction(st,m)} function done(t){return new Promise((a,b)=>{t.oncomplete=a;t.onerror=()=>b(t.error);t.onabort=()=>b(t.error)})}
async function openDB(){db=await new Promise((a,b)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>['meta','clips','chunks'].forEach(n=>{if(!r.result.objectStoreNames.contains(n))r.result.createObjectStore(n)});r.onsuccess=()=>a(r.result);r.onerror=()=>b(r.error)});return req(tx(['meta']).objectStore('meta').get('header'))}
async function derive(p,s){let b=await crypto.subtle.importKey('raw',enc.encode(p),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:s,iterations:350000,hash:'SHA-256'},b,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function seal(u,a){let iv=crypto.getRandomValues(new Uint8Array(12)),d=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode(a)},key,u);return{iv:b64(iv),data:b64(new Uint8Array(d))}}
async function unseal(x,a){return new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb(x.iv),additionalData:enc.encode(a)},key,unb(x.data)))}
async function createVault(p){if(p.length<12)throw Error('Use at least 12 characters.');let salt=crypto.getRandomValues(new Uint8Array(16));key=await derive(p,salt);let sent=await seal(enc.encode('ok'),'sentinel'),t=tx(['meta'],'readwrite');t.objectStore('meta').put({salt:b64(salt),sent},'header');await done(t);await restore();render()}
async function unlock(p){let h=await req(tx(['meta']).objectStore('meta').get('header'));key=await derive(p,unb(h.salt));await unseal(h.sent,'sentinel');await restore();render()}
async function restore(){S.clips=[];for(const id of await req(tx(['clips']).objectStore('clips').getAllKeys())){let r=await req(tx(['clips']).objectStore('clips').get(id)),m=JSON.parse(dec.decode(await unseal(r,`meta/${id}`)));S.clips.push({...m,id,url:null})}}
async function getBlob(c){let parts=[];for(let i=0;i<c.count;i++){let r=await req(tx(['chunks']).objectStore('chunks').get(`${c.id}:${i}`));parts.push((await unseal(r,`chunk/${c.id}/${i}`)).buffer)}return new Blob(parts,{type:c.type})}
async function probe(blob){let v=document.createElement('video');v.preload='metadata';v.src=URL.createObjectURL(blob);await new Promise((a,b)=>{v.onloadedmetadata=a;v.onerror=b});let o={duration:v.duration,width:v.videoWidth,height:v.videoHeight};URL.revokeObjectURL(v.src);return o}
async function importFile(f){let id=crypto.randomUUID(),count=Math.ceil(f.size/CHUNK);for(let i=0;i<count;i++){let u=new Uint8Array(await f.slice(i*CHUNK,Math.min(f.size,(i+1)*CHUNK)).arrayBuffer()),c=await seal(u,`chunk/${id}/${i}`),t=tx(['chunks'],'readwrite');t.objectStore('chunks').put(c,`${id}:${i}`);await done(t)}let info=await probe(f),m={name:f.name,size:f.size,type:f.type||'video/mp4',count,...info},c=await seal(enc.encode(JSON.stringify(m)),`meta/${id}`),t=tx(['clips'],'readwrite');t.objectStore('clips').put(c,id);await done(t);S.clips.push({...m,id,url:URL.createObjectURL(f)})}
async function sample(c){let blob=c.url?await fetch(c.url).then(r=>r.blob()):await getBlob(c),v=document.createElement('video');v.muted=true;v.src=URL.createObjectURL(blob);await new Promise((a,b)=>{v.onloadedmetadata=a;v.onerror=b});let cv=document.createElement('canvas');cv.width=96;cv.height=54;let x=cv.getContext('2d',{willReadFrequently:true}),n=Math.max(8,Math.min(100,Math.ceil(c.duration*4))),out=[];for(let i=0;i<n;i++){let t=Math.min(c.duration-.03,i*(c.duration-.03)/Math.max(1,n-1));v.currentTime=t;await new Promise(a=>v.onseeked=a);x.drawImage(v,0,0,96,54);out.push(descriptor(x.getImageData(0,0,96,54).data,96,54,t))}URL.revokeObjectURL(v.src);return out}
async function makeGreat(){if(S.busy)return;S.busy=true;S.msg='Analyzing real frames locally…';render();try{for(let c of S.clips)S.analyses.set(c.id,await sample(c));S.overlaps=[];for(let i=0;i<S.clips.length;i++)for(let j=0;j<S.clips.length;j++)if(i!=j){let a=S.clips[i],b=S.clips[j],m=detectOverlap(S.analyses.get(a.id),S.analyses.get(b.id));if(m)S.overlaps.push({a:a.id,b:b.id,match:m})}let e=S.clips.map(c=>({...c,samples:S.analyses.get(c.id)})),order=bestOrder(e);S.plan=makePlan(e,order,S.overlaps);S.msg='Plan ready. High-confidence overlaps are merged; uncertain ones are kept.'}catch(e){S.msg=e.message}finally{S.busy=false;render()}}
async function removeClip(id){if(!confirm('Delete Cutroom’s encrypted copy? Your original is untouched.'))return;let t=tx(['clips','chunks'],'readwrite');t.objectStore('clips').delete(id);for(const k of await req(t.objectStore('chunks').getAllKeys()))if(String(k).startsWith(id+':'))t.objectStore('chunks').delete(k);await done(t);let c=S.clips.find(x=>x.id===id);if(c?.url)URL.revokeObjectURL(c.url);S.clips=S.clips.filter(x=>x.id!==id);S.plan=null;S.overlaps=[];render()}
function esc(s=''){return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function render(){let a=$('#app'),brand='<div class=brand><div class=logo>C</div><div><h1>Cutroom</h1><p>Independent · local-first</p></div></div>',warn='<div class=\"card warning\"><b>Independent development build.</b> Use non-sensitive test clips until this exact build is verified on your iPhone. No cloud video-analysis API is used.</div>';if(!key){a.innerHTML=brand+warn+'<div class=\"card stack\"><h2>Local encrypted vault</h2><input id=p type=password placeholder=\"Passphrase — 12+ characters\"><button id=u>Unlock / Create</button><p class=muted>Your imported copies live in encrypted browser storage on this device.</p></div>';$('#u').onclick=async()=>{try{let h=await req(tx(['meta']).objectStore('meta').get('header'));h?await unlock($('#p').value):await createVault($('#p').value)}catch(e){alert(e.message||'Could not unlock')}};return}
let clips=S.clips.map(c=>`<div class=clip><div class=thumb></div><div><b>${esc(c.name)}</b><span class=muted>${c.duration.toFixed(1)}s · ${(c.size/1048576).toFixed(1)} MB</span></div><button class=\"secondary del\" data-id=\"${c.id}\">×</button></div>`).join('');
let review=S.overlaps.filter(o=>o.match.level==='review').map(o=>`<div class=decision>Possible repeat · ${o.match.duration.toFixed(2)}s · ${(o.match.confidence*100).toFixed(0)}% confidence. <b>Kept by default.</b></div>`).join('');
let plan=S.plan?`<div class=card><h2>Make It Great plan</h2>${S.plan.map((p,i)=>{let c=S.clips.find(x=>x.id===p.id);return`<div class=join><b>${i+1}. ${esc(c.name)}</b><div class=muted>${p.start.toFixed(2)}–${p.end.toFixed(2)}s</div></div>`}).join('')}${review}<p class=muted>Rendering/export is the next device-verification milestone. This build intentionally does not fake a finished export.</p></div>`:'';
a.innerHTML=brand+warn+`<div class=card><div class=row><button id=pick ${S.busy?'disabled':''}>Choose videos</button><button id=lock class=secondary>Lock</button></div><input id=file type=file accept=\"video/*\" multiple hidden><p class=muted>${S.clips.length} encrypted local clip(s)</p>${clips}</div><div class=card><button id=great class=primaryBig ${S.busy||!S.clips.length?'disabled':''}>Make It Great</button><p class=muted>Analyzes frames, searches for repeated footage, suggests order and cut points, and keeps uncertain duplicates.</p><p class=tiny>${esc(S.msg)}</p></div>${plan}<div class=card><h2>Storage</h2><p class=muted>${(S.clips.reduce((s,c)=>s+c.size,0)/1048576).toFixed(1)} MB of source video represented in Cutroom’s encrypted vault. Browser-managed storage may be cleared or evicted.</p></div>`;
$('#pick').onclick=()=>$('#file').click();$('#file').onchange=async e=>{S.busy=true;render();try{for(const f of [...e.target.files])await importFile(f);S.msg='Imported and encrypted locally.'}catch(x){S.msg=x.message}finally{S.busy=false;render()}};$('#lock').onclick=()=>{key=null;S.clips.forEach(c=>c.url&&URL.revokeObjectURL(c.url));S.clips=[];S.plan=null;render()};$('#great').onclick=makeGreat;document.querySelectorAll('.del').forEach(b=>b.onclick=()=>removeClip(b.dataset.id))}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'&&key){key=null;S.clips.forEach(c=>c.url&&URL.revokeObjectURL(c.url));S.clips=[];S.plan=null;render()}});
(async()=>{await openDB();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render()})().catch(e=>{document.querySelector('#app').innerHTML='<div class=card>Cutroom could not open local storage: '+esc(e.message)+'</div>'});
