import{descriptor,detectOverlap,bestOrder,makePlan}from"./core.mjs";
const $=s=>document.querySelector(s),S={clips:[],a:new Map,o:[],plan:null,busy:false,msg:"",screen:"studio"};let db,key=null,picker=false;const DB="cutroom-independent-v1",CH=4194304,E=new TextEncoder,D=new TextDecoder,b64=u=>btoa(String.fromCharCode(...u)),unb=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0)),req=r=>new Promise((a,b)=>{r.onsuccess=()=>a(r.result);r.onerror=()=>b(r.error)}),tx=(s,m="readonly")=>db.transaction(s,m),done=t=>new Promise((a,b)=>{t.oncomplete=a;t.onerror=()=>b(t.error)});
async function open(){db=await new Promise((a,b)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>["meta","clips","chunks"].forEach(n=>{if(!r.result.objectStoreNames.contains(n))r.result.createObjectStore(n)});r.onsuccess=()=>a(r.result);r.onerror=()=>b(r.error)})}
async function derive(p,s){let b=await crypto.subtle.importKey("raw",E.encode(p),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt:s,iterations:350000,hash:"SHA-256"},b,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
async function seal(u,a){let iv=crypto.getRandomValues(new Uint8Array(12)),d=await crypto.subtle.encrypt({name:"AES-GCM",iv,additionalData:E.encode(a)},key,u);return{iv:b64(iv),data:b64(new Uint8Array(d))}}
async function unseal(x,a){return new Uint8Array(await crypto.subtle.decrypt({name:"AES-GCM",iv:unb(x.iv),additionalData:E.encode(a)},key,unb(x.data)))}
async function restore(){S.clips=[];for(const id of await req(tx(["clips"]).objectStore("clips").getAllKeys())){let x=await req(tx(["clips"]).objectStore("clips").get(id)),m=JSON.parse(D.decode(await unseal(x,`meta/${id}`)));S.clips.push({...m,id,url:null})}}
async function login(p){let h=await req(tx(["meta"]).objectStore("meta").get("header"));if(!h){if(p.length<12)throw Error("Use at least 12 characters.");let salt=crypto.getRandomValues(new Uint8Array(16));key=await derive(p,salt);let sent=await seal(E.encode("ok"),"sentinel"),t=tx(["meta"],"readwrite");t.objectStore("meta").put({salt:b64(salt),sent},"header");await done(t)}else{try{key=await derive(p,unb(h.salt));await unseal(h.sent,"sentinel")}catch{key=null;throw Error("That password doesn't unlock this vault.")}}await restore();render()}
async function purge(id){let t=tx(["clips","chunks"],"readwrite");t.objectStore("clips").delete(id);for(const k of await req(t.objectStore("chunks").getAllKeys()))if(String(k).startsWith(id+":"))t.objectStore("chunks").delete(k);await done(t)}
async function probe(f){let v=document.createElement("video"),u=URL.createObjectURL(f);v.preload="metadata";v.src=u;await new Promise((a,b)=>{v.onloadedmetadata=a;v.onerror=()=>b(Error("iPhone could not read this clip."))});let z={duration:v.duration,width:v.videoWidth,height:v.videoHeight};URL.revokeObjectURL(u);return z}
async function add(fs){S.busy=true;let ok=0;try{for(let n=0;n<fs.length;n++){let f=fs[n],id=crypto.randomUUID();S.msg=`Encrypting video ${n+1} of ${fs.length}…`;render();try{let info=await probe(f),count=Math.ceil(f.size/CH);for(let i=0;i<count;i++){let c=await seal(new Uint8Array(await f.slice(i*CH,Math.min(f.size,(i+1)*CH)).arrayBuffer()),`chunk/${id}/${i}`),t=tx(["chunks"],"readwrite");t.objectStore("chunks").put(c,`${id}:${i}`);await done(t)}let m={name:f.name,size:f.size,type:f.type||"video/mp4",count,...info},c=await seal(E.encode(JSON.stringify(m)),`meta/${id}`),t=tx(["clips"],"readwrite");t.objectStore("clips").put(c,id);await done(t);S.clips.push({...m,id,url:URL.createObjectURL(f)});ok++}catch(e){await purge(id).catch(()=>{});throw e}}S.msg=`${ok} video${ok===1?"":"s"} ready.`}catch(e){S.msg=`Imported ${ok} of ${fs.length}. ${e.message}`}finally{S.busy=false;render()}}
async function blob(c){let p=[];for(let i=0;i<c.count;i++){let x=await req(tx(["chunks"]).objectStore("chunks").get(`${c.id}:${i}`));p.push((await unseal(x,`chunk/${c.id}/${i}`)).buffer)}return new Blob(p,{type:c.type})}
async function sample(c){let b=c.url?await fetch(c.url).then(r=>r.blob()):await blob(c),v=document.createElement("video"),u=URL.createObjectURL(b);v.muted=true;v.src=u;await new Promise((a,z)=>{v.onloadedmetadata=a;v.onerror=z});let cv=document.createElement("canvas");cv.width=96;cv.height=54;let x=cv.getContext("2d",{willReadFrequently:true}),n=Math.max(8,Math.min(100,Math.ceil(c.duration*4))),out=[];for(let i=0;i<n;i++){let t=Math.min(c.duration-.03,i*(c.duration-.03)/Math.max(1,n-1));v.currentTime=t;await new Promise(a=>v.onseeked=a);x.drawImage(v,0,0,96,54);out.push(descriptor(x.getImageData(0,0,96,54).data,96,54,t))}URL.revokeObjectURL(u);return out}
async function create(){S.busy=true;S.screen="creating";render();try{for(let i=0;i<S.clips.length;i++){S.msg=`Analyzing video ${i+1} of ${S.clips.length}…`;render();S.a.set(S.clips[i].id,await sample(S.clips[i]))}S.o=[];for(let i=0;i<S.clips.length;i++)for(let j=0;j<S.clips.length;j++)if(i!==j){let a=S.clips[i],b=S.clips[j],m=detectOverlap(S.a.get(a.id),S.a.get(b.id));if(m)S.o.push({a:a.id,b:b.id,match:m})}let e=S.clips.map(c=>({...c,samples:S.a.get(c.id)}));S.plan=makePlan(e,bestOrder(e),S.o);S.screen="result"}catch(e){S.screen="studio";S.msg=e.message||"Create failed."}finally{S.busy=false;render()}}
function lock(){key=null;S.clips.forEach(c=>c.url&&URL.revokeObjectURL(c.url));S.clips=[];S.plan=null;S.screen="studio";render()}const esc=(s="")=>s.replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c])),head=()=>`<div class=top><div class=mark>C</div><div><h1>Cutroom</h1><span>Private editor · v0.3</span></div>${key?"<button id=lock class=ghost>Lock</button>":""}</div>`;
function render(){let a=$("#app");if(!key){a.innerHTML=head()+`<section class="panel login"><div class=eyebrow>PRIVATE VIDEO EDITOR</div><h2>Make your clips flow.</h2><p>Unlock once. Add videos. Create.</p><input id=p type=password placeholder=Password><button id=u class=primary>Unlock Cutroom</button><div id=err class=error></div></section>`;$("#u").onclick=async()=>{try{await login($("#p").value)}catch(e){$("#err").textContent=e.message}};return}if(S.screen==="creating"){a.innerHTML=head()+`<section class="panel"><div class=spinner></div><div class=eyebrow>CREATING</div><h2>Making it great…</h2><p>${esc(S.msg)}</p></section>`;$("#lock").onclick=lock;return}if(S.screen==="result"){a.innerHTML=head()+`<section class=panel><div class=eyebrow>EDIT READY</div><h2>Your edit is planned.</h2><div class=preview><div class=play>▶</div><span>Renderer verification is next.</span></div><button class="primary disabled" disabled>Save to Photos</button><button id=again class=secondary>Make Another</button></section>`;$("#again").onclick=()=>{S.screen="studio";render()};$("#lock").onclick=lock;return}let cs=S.clips.map((c,i)=>`<div class=clip><div class=num>${i+1}</div><div><b>${esc(c.name)}</b><small>${c.duration.toFixed(1)} sec · ${(c.size/1048576).toFixed(1)} MB</small></div></div>`).join("");a.innerHTML=head()+`<section class=panel><div class=eyebrow>NEW EDIT</div><h2>${S.clips.length?"Ready to create.":"Add your videos."}</h2><p>The Photos picker stays inside your unlocked import flow.</p><button id=add class=upload>＋ Add Videos</button><input id=file type=file accept="video/*" multiple hidden><div class=clips>${cs}</div>${S.msg?`<div class=status>${esc(S.msg)}</div>`:""}<button id=create class="primary ${!S.clips.length||S.busy?"disabled":""}" ${!S.clips.length||S.busy?"disabled":""}>Create</button></section>`;$("#add").onclick=()=>{picker=true;$("#file").click()};$("#file").onchange=async e=>{let fs=[...e.target.files];picker=false;e.target.value="";if(fs.length)await add(fs)};$("#create").onclick=create;$("#lock").onclick=lock}
document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="hidden"&&key&&!picker)lock()});(async()=>{await open();navigator.serviceWorker?.register("./sw.js").catch(()=>{});render()})().catch(e=>{$("#app").innerHTML=`<div class=error>${esc(e.message)}</div>`});