export const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
export function descriptor(rgba,w,h,t=0){const gx=8,gy=6,tile=new Float32Array(gx*gy),edge=new Float32Array(gx*gy);let mean=0,n=0,black=0,white=0;const gray=new Float32Array(w*h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,g=(rgba[i]*.2126+rgba[i+1]*.7152+rgba[i+2]*.0722)/255;gray[y*w+x]=g;mean+=g;n++;if(g<.03)black++;if(g>.97)white++}mean/=Math.max(1,n);for(let ty=0;ty<gy;ty++)for(let tx=0;tx<gx;tx++){let s=0,e=0,c=0;const x0=Math.floor(tx*w/gx),x1=Math.floor((tx+1)*w/gx),y0=Math.floor(ty*h/gy),y1=Math.floor((ty+1)*h/gy);for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const g=gray[y*w+x];s+=g;c++;if(x+1<w)e+=Math.abs(g-gray[y*w+x+1]);if(y+1<h)e+=Math.abs(g-gray[(y+1)*w+x])}tile[ty*gx+tx]=s/Math.max(1,c);edge[ty*gx+tx]=e/Math.max(1,c*2)}let variance=0;for(const v of gray)variance+=(v-mean)**2;variance/=Math.max(1,n);return{t,mean,variance,black:black/n,white:white/n,tile:[...tile],edge:[...edge]}}
const mad=(a,b)=>a.reduce((s,v,i)=>s+Math.abs(v-b[i]),0)/a.length;
export function frameSimilarity(a,b){if(!a||!b)return 0;const low=a.variance<.0008||b.variance<.0008||a.black>.93||b.black>.93||a.white>.93||b.white>.93;if(low)return 0;const spatial=1-clamp(mad(a.tile,b.tile)*2.6),edges=1-clamp(mad(a.edge,b.edge)*5),exposure=1-clamp(Math.abs(a.mean-b.mean)*1.5);return clamp(.58*spatial+.30*edges+.12*exposure)}
export function motion(seq){if(seq.length<2)return{kind:"unknown",speed:0,confidence:0,dx:0};const a=seq[0],b=seq.at(-1),dt=b.t-a.t;if(!(dt>0))return{kind:"unknown",speed:0,confidence:0,dx:0};const center=s=>{let sx=0,sw=0;for(let i=0;i<s.tile.length;i++){const x=i%8,w=Math.max(0,s.tile[i]-s.mean*.65);sx+=x*w;sw+=w}return sw?sx/sw:3.5};const dx=(center(b)-center(a))/7,speed=Math.abs(dx)/dt;return{kind:speed<.02?"still":"moving",speed,confidence:clamp((a.variance+b.variance)*15),dx}}
export function joinCost(a,b){const sim=frameSimilarity(a.frames.at(-1),b.frames[0]),ma=motion(a.frames),mb=motion(b.frames);let m=.45;if(ma.confidence>.2&&mb.confidence>.2){if(ma.kind==="still"&&mb.kind==="still")m=.08;else if(ma.kind!==mb.kind)m=.5;else if(ma.kind==="moving"&&mb.kind==="moving"){const sign=Math.sign(ma.dx)*Math.sign(mb.dx);m=sign<0?.95:clamp(Math.abs(ma.speed-mb.speed)/Math.max(.02,ma.speed,mb.speed))}}return clamp(.62*(1-sim)+.38*m)}
export function detectOverlap(A,B,{coarseThreshold=.82,denseThreshold=.86,minRun=4,minDuration=.75}={}){const hits=[];for(let i=0;i<A.length;i++)for(let j=0;j<B.length;j++){const s=frameSimilarity(A[i],B[j]);if(s>=coarseThreshold)hits.push({i,j,off:B[j].t-A[i].t,s})}if(hits.length<minRun)return null;const buckets=new Map;for(const h of hits){const k=Math.round(h.off/.18);if(!buckets.has(k))buckets.set(k,[]);buckets.get(k).push(h)}const groups=[...buckets.values()].sort((x,y)=>y.length-x.length);for(const g of groups){const sorted=g.sort((x,y)=>x.i-y.i||x.j-y.j);let run=[],best=[];for(const h of sorted){const p=run.at(-1);if(!p||(h.i>p.i&&h.j>p.j&&h.i-p.i<=3&&h.j-p.j<=3))run.push(h);else run=[h];if(run.length>best.length)best=[...run]}if(best.length<minRun)continue;const dur=Math.min(A[best.at(-1).i].t-A[best[0].i].t,B[best.at(-1).j].t-B[best[0].j].t),mean=best.reduce((s,h)=>s+h.s,0)/best.length;if(dur<minDuration)return{level:"review",confidence:mean,duration:Math.max(0,dur),aStart:A[best[0].i].t,aEnd:A[best.at(-1).i].t,bStart:B[best[0].j].t,bEnd:B[best.at(-1).j].t};const ma=motion(A.slice(best[0].i,best.at(-1).i+1)),mb=motion(B.slice(best[0].j,best.at(-1).j+1));if(ma.confidence>.2&&mb.confidence>.2&&ma.kind==="moving"&&mb.kind==="moving"&&Math.sign(ma.dx)*Math.sign(mb.dx)<0)return null;const variation=A.slice(best[0].i,best.at(-1).i+1).some((x,k,arr)=>k&&frameSimilarity(x,arr[k-1])<.985);if(!variation)return null;return{level:mean>=denseThreshold?"high":"review",confidence:mean,duration:dur,aStart:A[best[0].i].t,aEnd:A[best.at(-1).i].t,bStart:B[best[0].j].t,bEnd:B[best.at(-1).j].t}}return null}
export function bestOrder(clips){if(clips.length<2)return clips.map(c=>c.id);const ids=clips.map(c=>c.id),by=new Map(clips.map(c=>[c.id,c])),cost=(x,y)=>joinCost({frames:by.get(x).samples.slice(-3)},{frames:by.get(y).samples.slice(0,3)});if(ids.length>8){const left=new Set(ids.slice(1)),out=[ids[0]];while(left.size){const last=out.at(-1);let best=null,bc=9;for(const x of left){const c=cost(last,x);if(c<bc){bc=c;best=x}}out.push(best);left.delete(best)}return out}let best=ids,bc=Infinity;const perm=(arr,rest)=>{if(!rest.length){let c=0;for(let i=0;i+1<arr.length;i++)c+=cost(arr[i],arr[i+1]);if(c<bc){bc=c;best=[...arr]}return}for(const x of rest)perm([...arr,x],rest.filter(y=>y!==x))};perm([],ids);return best}
// Legacy entry point: sparse overlap candidates alone never authorize a trim.
export function makePlan(clips,order){const by=new Map(clips.map(c=>[c.id,c]));return order.map(id=>({id,start:0,end:by.get(id).duration}))}
